// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJCx4mUg6DagNlL_0UM8Ynmh62Tm7TrR4',
    appId: '1:712998573671:web:2107abe478680d613d26c2',
    messagingSenderId: '712998573671',
    projectId: 'acik-soru',
    authDomain: 'acik-soru.firebaseapp.com',
    storageBucket: 'acik-soru.appspot.com',
    measurementId: 'G-65WF22H3VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFv59E0G-_62fEB9wmnjCMD4REH1WgCYQ',
    appId: '1:712998573671:android:68a2b89e86eae2f33d26c2',
    messagingSenderId: '712998573671',
    projectId: 'acik-soru',
    storageBucket: 'acik-soru.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACUZpBQajNGrf3c3HwfzbSpaBWHECfRHs',
    appId: '1:712998573671:ios:786c970720ffbe903d26c2',
    messagingSenderId: '712998573671',
    projectId: 'acik-soru',
    storageBucket: 'acik-soru.appspot.com',
    iosBundleId: 'com.example.acikSoru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACUZpBQajNGrf3c3HwfzbSpaBWHECfRHs',
    appId: '1:712998573671:ios:51fe975c77fc64533d26c2',
    messagingSenderId: '712998573671',
    projectId: 'acik-soru',
    storageBucket: 'acik-soru.appspot.com',
    iosBundleId: 'com.example.acikSoru.RunnerTests',
  );
}
